const Store = require('electron-store');
const { v4: uuidv4 } = require('uuid');
const store = new Store({ name: 'y2k-deskcal-settings', defaults: { todos: [], events: [{ id:'sample-1', title:'Sample reminder', notes:'This is a local event. Delete it when you add your own.', startTime:new Date(Date.now()+60*60*1000).toISOString(), reminderMinutes:60, remindedAt:null, snoozedUntil:null, source:'local' }], settings: { reminderPollSeconds:30, defaultReminderMinutes:60, theme:'y2k-purple' } } });
function getStoreSnapshot(){ return { todos:store.get('todos',[]), events:store.get('events',[]), settings:store.get('settings',{}) }; }
function saveEvent(input){ const events=store.get('events',[]); const now=new Date().toISOString(); const eventData={ id:input.id||uuidv4(), title:String(input.title||'Untitled event').trim(), notes:String(input.notes||'').trim(), startTime:input.startTime, reminderMinutes:Number(input.reminderMinutes||60), remindedAt:input.remindedAt||null, snoozedUntil:input.snoozedUntil||null, source:input.source||'local', updatedAt:now, createdAt:input.createdAt||now }; const idx=events.findIndex(e=>e.id===eventData.id); if(idx>=0) events[idx]={...events[idx],...eventData}; else events.push(eventData); store.set('events', events); return eventData; }
function deleteEvent(id){ store.set('events', store.get('events',[]).filter(e=>e.id!==id)); return {ok:true}; }
function saveTodo(input){ const todos=store.get('todos',[]); const now=new Date().toISOString(); const todo={ id:input.id||uuidv4(), text:String(input.text||'').trim(), important:Boolean(input.important), completed:Boolean(input.completed), dueDate:input.dueDate||'', createdAt:input.createdAt||now, updatedAt:now }; if(!todo.text) throw new Error('Todo text is required.'); const idx=todos.findIndex(t=>t.id===todo.id); if(idx>=0) todos[idx]={...todos[idx],...todo}; else todos.unshift(todo); store.set('todos',todos); return todo; }
function updateTodo(input){ const todos=store.get('todos',[]); const idx=todos.findIndex(t=>t.id===input.id); if(idx<0) return {ok:false,error:'Todo not found.'}; todos[idx]={...todos[idx],...input,updatedAt:new Date().toISOString()}; store.set('todos',todos); return todos[idx]; }
function deleteTodo(id){ store.set('todos', store.get('todos',[]).filter(t=>t.id!==id)); return {ok:true}; }
function snoozeReminder(eventId, minutes){ const events=store.get('events',[]); const event=events.find(e=>e.id===eventId); if(!event) return {ok:false,error:'Event not found.'}; event.snoozedUntil=new Date(Date.now()+Number(minutes)*60*1000).toISOString(); event.remindedAt=null; store.set('events',events); return {ok:true,event}; }
function markEventReminded(eventId){ const events=store.get('events',[]); const event=events.find(e=>e.id===eventId); if(!event) return {ok:false,error:'Event not found.'}; event.remindedAt=new Date().toISOString(); event.snoozedUntil=null; store.set('events',events); return {ok:true,event}; }
function initStoreHandlers(ipcMain){ ipcMain.handle('store:get',()=>getStoreSnapshot()); ipcMain.handle('event:save',(e,input)=>saveEvent(input)); ipcMain.handle('event:delete',(e,id)=>deleteEvent(id)); ipcMain.handle('todo:save',(e,input)=>saveTodo(input)); ipcMain.handle('todo:update',(e,input)=>updateTodo(input)); ipcMain.handle('todo:delete',(e,id)=>deleteTodo(id)); ipcMain.handle('settings:save',(e,input)=>{ const settings={...store.get('settings',{}),...input}; store.set('settings',settings); return settings; }); }
module.exports={ initStoreHandlers,getStoreSnapshot,saveEvent,deleteEvent,saveTodo,updateTodo,deleteTodo,snoozeReminder,markEventReminded };
