import { useEffect, useMemo, useState } from 'react';
import CalendarGrid from './components/CalendarGrid.jsx';
import TodoPad from './components/TodoPad.jsx';
import EventPanel from './components/EventPanel.jsx';
import ReminderModal from './components/ReminderModal.jsx';
import { getMonthLabel } from './utils/calendar.js';
export default function App(){
 const [currentDate,setCurrentDate]=useState(new Date()); const [events,setEvents]=useState([]); const [todos,setTodos]=useState([]); const [settings,setSettings]=useState({}); const [selectedDate,setSelectedDate]=useState(new Date()); const [activeReminder,setActiveReminder]=useState(null);
 async function loadData(){ const snapshot=await window.deskcal.getStore(); setEvents(snapshot.events||[]); setTodos(snapshot.todos||[]); setSettings(snapshot.settings||{}); }
 useEffect(()=>{ loadData(); const removeData=window.deskcal.onDataChanged(s=>{setEvents(s.events||[]);setTodos(s.todos||[]);setSettings(s.settings||{});}); const removeRing=window.deskcal.onReminderRing(({event,bellUrl,bellPath})=>{ setActiveReminder(event); try{ const audio=new Audio(bellUrl || `file:///${String(bellPath || '').replace(/\\/g,'/')}`); audio.volume=.85; audio.currentTime=0; audio.play().catch((error)=>console.error('Bell sound failed to play:', error)); }catch(error){ console.error('Bell sound error:', error); } }); const removeFocus=window.deskcal.onReminderFocus(event=>setActiveReminder(event)); return ()=>{removeData();removeRing();removeFocus();}; },[]);
 const selectedDateEvents=useMemo(()=>events.filter(event=>event.startTime && new Date(event.startTime).toDateString()===selectedDate.toDateString()),[events,selectedDate]);
 const goToToday=()=>{ const today=new Date(); setCurrentDate(today); setSelectedDate(today); };
 return <main className="app-shell"><section className="top-bar"><div><p className="eyebrow">SYSTEM TRAY CALENDAR // LOCAL MODE</p><h1>Y2K DeskCal</h1></div><div className="top-actions"><button className="button ghost" onClick={goToToday}>Today</button><button className="button ghost" onClick={()=>window.deskcal.testNotification()}>Test Bell</button><button className="button hot" onClick={()=>window.deskcal.hideWindow()}>Hide to Tray</button></div></section><section className="calendar-toolbar"><button className="button icon" onClick={()=>setCurrentDate(new Date(currentDate.getFullYear(),currentDate.getMonth()-1,1))}>‹</button><div className="month-title">{getMonthLabel(currentDate)}</div><button className="button icon" onClick={()=>setCurrentDate(new Date(currentDate.getFullYear(),currentDate.getMonth()+1,1))}>›</button></section><section className="workspace"><div className="calendar-window"><div className="window-titlebar"><span>MONTH_VIEW.EXE</span><span className="window-controls">_ □ ×</span></div><CalendarGrid currentDate={currentDate} selectedDate={selectedDate} events={events} onSelectDate={setSelectedDate}/></div><aside className="side-stack"><TodoPad todos={todos} onSaveTodo={async t=>{await window.deskcal.saveTodo(t); await loadData();}} onUpdateTodo={async t=>{await window.deskcal.updateTodo(t); await loadData();}} onDeleteTodo={async id=>{await window.deskcal.deleteTodo(id); await loadData();}}/><EventPanel selectedDate={selectedDate} events={selectedDateEvents} defaultReminderMinutes={settings.defaultReminderMinutes||60} onSaveEvent={async e=>{await window.deskcal.saveEvent(e); await loadData();}} onDeleteEvent={async id=>{await window.deskcal.deleteEvent(id); await loadData();}}/></aside></section>{activeReminder && <ReminderModal event={activeReminder} onDismiss={()=>setActiveReminder(null)} onSnooze={async minutes=>{await window.deskcal.snoozeReminder(activeReminder.id,minutes); setActiveReminder(null); await loadData();}}/>}</main>;
}
